"""Defaults das regras de alerta (R1–R5) — espelham AlertRuleConfig + SQL stores."""

from __future__ import annotations

R1_MIN_CHECKOUT_DURATION_SEC = 20.0
POS_MATCH_DELTA_SEC = 20
T_RETURN_SEC = 1800.0
R3_VISUAL_MARGIN = 2
CARRY_CONFIDENCE_THRESHOLD = 0.55
R4_MIN_ITEMS = 5
R4_FAST_DURATION_SEC = 90.0
ENABLE_R4 = True
R5_CANCELLED_DELTA_SEC = 60
BUFFER_BEFORE_SEC = 20.0
BUFFER_AFTER_SEC = 20.0
CHECKOUT_BUFFER_BEFORE_SEC = 5.0
CHECKOUT_BUFFER_AFTER_SEC = 5.0
VID_STRIDE = 5
