apiVersion: v1
kind: Secret
metadata:
  name: track-fraude-secrets
  namespace: track-fraude
type: Opaque
stringData:
  secret-key: CHANGE_ME_RANDOM_SECRET
  rabbitmq-url: amqp://track_fraude:track_fraude@rabbitmq.track-fraude.svc.cluster.local:5672/%2F
  postgres-url: postgresql://track_fraude:track_fraude@postgres.track-fraude.svc.cluster.local:5432/track_fraude
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: track-fraude-config
  namespace: track-fraude
data:
  settings.yaml: |
    app:
      name: track_fraude
      host: 0.0.0.0
      port: 8080
      secret_key: CHANGE_ME_RANDOM_SECRET

    database:
      path: /app/data/track_fraude.db

    auth:
      admin_username: admin
      admin_password: admin123
      admin_display_name: Administrador

    pipeline:
      mode: queue
      python:
      queue_url: amqp://track_fraude:track_fraude@rabbitmq.track-fraude.svc.cluster.local:5672/%2F
      queue_name: track-fraude-pipelines
