apiVersion: v1
kind: Secret
metadata:
  name: track-fraude-secrets
  namespace: track-fraude
type: Opaque
stringData:
  secret-key: 85b85c880b4298d3758f23bae369dcbd07eb69e82da188d37ef09a669a18938f
  rabbitmq-url: amqp://track_fraude:track_fraude@192.168.0.199:5672/%2F
  postgres-url: postgresql://track_fraude:track_fraude@192.168.0.199:5432/track_fraude
  atlas-api-key: atlas-dev-internal-key
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: track-fraude-config
  namespace: track-fraude
data:
  settings.yaml: |
    app:
      name: track_fraude
      host: 0.0.0.0
      port: 8080
      secret_key: 85b85c880b4298d3758f23bae369dcbd07eb69e82da188d37ef09a669a18938f

    database:
      backend: postgres
      postgres_url: postgresql://track_fraude:track_fraude@192.168.0.199:5432/track_fraude

    auth:
      admin_username: admin
      admin_password: admin123
      admin_display_name: Administrador

    pipeline:
      mode: queue
      python:

    atlas:
      api_url: http://atlas-platform-api:8090
      api_key: atlas-dev-internal-key
