apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: track-fraude
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: track_fraude
            - name: RABBITMQ_DEFAULT_PASS
              value: track_fraude
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: track-fraude
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: track-fraude
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: track_fraude
            - name: POSTGRES_USER
              value: track_fraude
            - name: POSTGRES_PASSWORD
              value: track_fraude
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: track-fraude
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
