apiVersion: v1
kind: PersistentVolume
metadata:
  name: track-fraude-data-nfs
spec:
  storageClassName: track-fraude-nfs
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.199
    path: /srv/track_fraude/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: track-fraude-data
  namespace: track-fraude
spec:
  storageClassName: track-fraude-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  volumeName: track-fraude-data-nfs
